package expo.modules.glasssdk.glass.vendors.k900

import android.content.Context
import android.net.wifi.WifiManager
import android.os.Build
import android.os.Handler
import android.util.Log

/**
 * Wraps WifiManager.startLocalOnlyHotspot() (API 26+).
 * Phone creates a local hotspot while keeping its existing WiFi connected.
 * SSID/password are auto-generated by the OS — no user input needed.
 */
class LocalHotspotManager(private val context: Context) {

    companion object {
        private const val TAG = "[Glass:LocalHotspot]"
    }

    interface Callback {
        fun onStarted(ssid: String, password: String)
        fun onFailed(reason: String)
    }

    private var reservation: WifiManager.LocalOnlyHotspotReservation? = null
    private val wifiManager = context.applicationContext
        .getSystemService(Context.WIFI_SERVICE) as WifiManager

    fun start(handler: Handler, callback: Callback) {
        stop()
        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.O) {
            callback.onFailed("Local hotspot requires Android 8+")
            return
        }
        Log.d(TAG, "Starting local-only hotspot")
        wifiManager.startLocalOnlyHotspot(object : WifiManager.LocalOnlyHotspotCallback() {
            override fun onStarted(r: WifiManager.LocalOnlyHotspotReservation) {
                reservation = r
                val (ssid, pwd) = extractCredentials(r)
                if (ssid.isEmpty() || pwd.isEmpty()) {
                    Log.e(TAG, "Could not extract credentials from hotspot reservation")
                    callback.onFailed("Could not read hotspot credentials")
                    return
                }
                Log.d(TAG, "Local hotspot started: $ssid")
                callback.onStarted(ssid, pwd)
            }

            override fun onFailed(reason: Int) {
                Log.e(TAG, "Local hotspot failed, reason=$reason")
                callback.onFailed("Hotspot error: $reason")
            }

            override fun onStopped() {
                Log.d(TAG, "Local hotspot stopped")
            }
        }, handler)
    }

    fun stop() {
        reservation?.close()
        reservation = null
        Log.d(TAG, "Local hotspot released")
    }

    @Suppress("DEPRECATION")
    private fun extractCredentials(r: WifiManager.LocalOnlyHotspotReservation): Pair<String, String> {
        return if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
            val cfg = r.softApConfiguration
            Pair(cfg.ssid ?: "", cfg.passphrase ?: "")
        } else {
            val cfg = r.wifiConfiguration
            val ssid = cfg?.SSID?.trim('"') ?: ""
            val pwd = cfg?.preSharedKey?.trim('"') ?: ""
            Pair(ssid, pwd)
        }
    }
}
